# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-27 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Man',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(blank=True, db_column=b'BARCODE', max_length=20, null=True)),
                ('volret', models.CharField(blank=True, db_column=b'VOLRET', max_length=20, null=True)),
                ('state', models.CharField(blank=True, db_column=b'STATE', max_length=20, null=True)),
                ('flags', models.CharField(blank=True, db_column=b'FLAGS', max_length=20, null=True)),
                ('ip', models.CharField(blank=True, db_column=b'IP', max_length=20, null=True)),
                ('capacity', models.CharField(blank=True, db_column=b'CAPACITY', max_length=20, null=True)),
                ('typefull', models.CharField(blank=True, db_column=b'TYPEFULL', max_length=20, null=True)),
                ('name', models.CharField(blank=True, db_column=b'NAME', max_length=200, null=True)),
                ('clretent', models.CharField(blank=True, db_column=b'CLRETENT', max_length=20, null=True)),
            ],
            options={
                'db_table': 'MAN',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(blank=True, db_column=b'BARCODE', max_length=20, null=True)),
                ('volret', models.CharField(blank=True, db_column=b'VOLRET', max_length=20, null=True)),
                ('state', models.CharField(blank=True, db_column=b'STATE', max_length=20, null=True)),
                ('flags', models.CharField(blank=True, db_column=b'FLAGS', max_length=20, null=True)),
                ('ip', models.CharField(blank=True, db_column=b'IP', max_length=20, null=True)),
                ('capacity', models.CharField(blank=True, db_column=b'CAPACITY', max_length=20, null=True)),
                ('typefull', models.CharField(blank=True, db_column=b'TYPEFULL', max_length=20, null=True)),
                ('name', models.CharField(blank=True, db_column=b'NAME', max_length=50, null=True)),
                ('clretent', models.CharField(blank=True, db_column=b'CLRETENT', max_length=20, null=True)),
            ],
            options={
                'db_table': 'MANUAL',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Masterlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(db_column=b'BARCODE', max_length=20)),
            ],
            options={
                'db_table': 'MASTERLIST',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Masterlist1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(blank=True, db_column=b'BARCODE', max_length=20, null=True)),
            ],
            options={
                'db_table': 'MASTERLIST1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(db_column=b'BARCODE', max_length=20)),
                ('volret', models.CharField(blank=True, db_column=b'VOLRET', max_length=20, null=True)),
                ('state', models.CharField(blank=True, db_column=b'STATE', max_length=20, null=True)),
                ('flags', models.CharField(blank=True, db_column=b'FLAGS', max_length=20, null=True)),
                ('ip', models.CharField(db_column=b'IP', max_length=20)),
            ],
            options={
                'db_table': 'NETWORK',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Network1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(blank=True, db_column=b'BARCODE', max_length=20, null=True)),
                ('volret', models.CharField(blank=True, db_column=b'VOLRET', max_length=20, null=True)),
                ('state', models.CharField(blank=True, db_column=b'STATE', max_length=2, null=True)),
                ('flags', models.CharField(blank=True, db_column=b'FLAGS', max_length=20, null=True)),
                ('ip', models.CharField(blank=True, db_column=b'IP', max_length=20, null=True)),
                ('capacity', models.CharField(blank=True, db_column=b'CAPACITY', max_length=30, null=True)),
                ('typefull', models.CharField(blank=True, db_column=b'TYPEFULL', max_length=30, null=True)),
            ],
            options={
                'db_table': 'NETWORK1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Discarded',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Barcode', models.CharField(db_column=b'Barcode', max_length=20)),
            ],
            options={
                'db_table': 'Discard',
                'managed': True,
            },
        ),
    ]
