# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-27 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discarded',
            name='Barcode',
            field=models.CharField(blank=True, db_column=b'Barcode', max_length=20),
        ),
    ]
