# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-27 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='zonegroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(max_length=30)),
                ('Class', models.CharField(max_length=30)),
                ('FabricName', models.CharField(max_length=100)),
                ('FabricA', models.CharField(max_length=100)),
                ('FabricB', models.CharField(max_length=100)),
            ],
            options={
                'managed': True,
            },
        ),
    ]
