# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-23 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0004_auto_20181023_0517'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostgroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Host', models.CharField(max_length=100)),
                ('FabricName', models.CharField(max_length=30)),
                ('Class', models.CharField(max_length=30)),
                ('Vsan', models.CharField(max_length=50)),
                ('Wwn', models.CharField(max_length=100)),
            ],
            options={
                'managed': True,
            },
        ),
    ]
