# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-23 11:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0005_hostgroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostgroup',
            old_name='Host',
            new_name='HostName',
        ),
    ]
